### ISSUE TITLE
Question - why not custom tasks?

### ISSUE THREAD

**Issue by benjamincburns** [builttoroam/pipeline_templates#42]
It looks like this is meant to be a reusable library of bicep templates. Just curious, but have you considered writing custom tasks instead of templates? If so, I'd be curious to know why you went with templates over tasks?

This project is really great, so please don't take my question as an implicit "bah! they're doing it wrong!" I just was having a read through your `bicep-*.yml` files and noticed how much conditional stuff there is, checks and safeguards, etc, and I wondered if you might have an easier time with custom tasks instead.

**Comment by nickrandolph** [comment]
Hi @benjamincburns - firstly my apologies for only just getting to this. github notifications go to junk because I get so many of them, so I only saw this issue when I jumped on today. 
The issue with custom tasks is that it becomes almost impossible for someone to override the behaviour and/or extend the task. With templates, if the template doesn't exactly fit, you can simply copy it, modify it and off you go. 
As you point out there's a lot of conditional stuff in there, and some smarts for catching issues that are specific to mobile builds. The idea with each of the templates is that you can drop them into your pipeline, pass it a bunch of variables and you should be good to go for the task you want to achieve. I feel that tasks are great for accomplishing specific things eg build a project but they're not good when you want to combine multiple steps for an entire pipeline.

**Comment by benjamincburns** [comment]
No worries on the delay, especially since my question was very not urgent - just seemed like an opportunity to learn something.

Cheers!
